### ISSUE TITLE
Suporte atualização do site https://www.car.gov.br/

### ISSUE THREAD

**Issue by salesHgabriel** [urbanogilson/SICAR#21]
Devido às atualizações do site ocorreram algum tipo impacto no package ? 

abaixo imagem de algumas mudanças

![image](https://github.com/urbanogilson/SICAR/assets/40372526/6dfcef3a-8a7b-41f9-8d7f-c8dacab28d32)

**Comment by urbanogilson** [comment]
Houve um grande impacto porque o suporte para download de cidades não está funcionando
A atualização do pacote está a caminho
