### ISSUE TITLE
Errors When Downloading Data with SICAR Python Package in Google Colab

### ISSUE THREAD

**Issue by erickfaria** [urbanogilson/SICAR#25]
## Description
Encountering multiple errors when using the SICAR Python package in Google Colab, as per the repository examples.

## Steps to Reproduce
1. Installed the SICAR package and dependencies in Google Colab:
   ```bash
   !pip install git+https://github.com/urbanogilson/SICAR --quiet
   !sudo apt install tesseract-ocr -y --quiet

Ran code to download data for various Brazilian states and polygons:
```python
from SICAR import Sicar, Polygon, State
from google.colab import drive

drive.mount('/content/drive')
car = Sicar()

result = car.download_state(state=State.RR, polygon=Polygon.APPS, folder='drive/MyDrive/SICAR/RR')
```
Script failed with errors for each state and polygon:
Resulting in UrlNotOkException:
```bash
---------------------------------------------------------------------------
UrlNotOkException                         Traceback (most recent call last)
[<ipython-input-7-7544f9d02125>](https://localhost:8080/#) in <cell line: 1>()
----> 1 result = car.download_state(state=State.RR, polygon=Polygon.APPS, folder='drive/MyDrive/SICAR/RR')

2 frames
[/usr/local/lib/python3.10/dist-packages/SICAR/sicar.py](https://localhost:8080/#) in _get(self, url, *args, **kwargs)
    125 
    126         if not response.ok:
--> 127             raise UrlNotOkException(url)
    128 
    129         return response

UrlNotOkException: Oh no! Failed to access https://www.car.gov.br/publico/municipios/ReCaptcha?id=685252!
```

## Environment
Google Colab
Python version: 3.12
SICAR package version: 0.7.0

## Additional Context
SICAR server was operational, indicating an issue with the package or its interaction with Google Colab.

**Comment by urbanogilson** [comment]
The SICAR server is not fully operational.

Even if you try to download manually, the captcha doesn't load.

![image](https://github.com/urbanogilson/SICAR/assets/16805527/dfd8eb90-455e-4a77-af4e-51be204da460)

Could you check if this is the case on your machine?

**Comment by urbanogilson** [comment]
The problem was on the SICAR website, but it appears to have already been resolved

**Comment by erickfaria** [comment]
I wanted to provide an update regarding the issue we were experiencing. The problem was indeed on the SICAR website. Fortunately, it appears that the issue has now been resolved.

I wanted to extend my gratitude for your attention.
