### ISSUE TITLE
Download a partir da imagem docker

### ISSUE THREAD

**Issue by DevDiegoSR** [urbanogilson/SICAR#26]
Olá Gilson,

Estou tentando realizar o download a partir da imagem docker, no entanto está caindo nesta exceção:
UrlNotOkException => Oh no! Failed to access https://www.car.gov.br/publico/municipios/ReCaptcha?id=171599!

```python
from SICAR import Sicar, State, Polygon
from SICAR.drivers import Paddle

car = Sicar(driver=Paddle)
car.download_state(State.AM, Polygon.HYDROGRAPHY, folder="AM")
```

Aparentemente o status da resposta não é 200, você conseguiria por favor me ajudar?

Verificando o site do sicar quando acessa o endpoint https://www.car.gov.br/publico/municipios/ReCaptcha?id=171599 por exemplo está retornando 401 Unauthorized, infelizmente deve ser isso a razão de cair na exceção.

![image](https://github.com/urbanogilson/SICAR/assets/143976579/91e2a044-5f42-465f-9588-6188c6251a5a)

REQUEST HEADERS
GET /publico/municipios/ReCaptcha?id=179130 HTTP/1.1
Accept: image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: pt-BR,pt;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Connection: keep-alive
Cookie: PLAY_SESSION=8a3c3e23418d613b6deb7c49513aaad7d8d9a45b-___ID=4baccb74-80b4-4972-822e-28d75799fe4c; _ga=GA1.3.630640521.1704282788; _gid=GA1.3.16703425.1705600373; _ga_CDHDQZB9ET=GS1.3.1705600373.2.1.1705600417.0.0.0
Host: www.car.gov.br
Referer: https://www.car.gov.br/publico/estados/downloads
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0
sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Microsoft Edge";v="120"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"

RESPONSE HEADERS
HTTP/1.1 401 Unauthorized
Server: nginx/1.12.2
Date: Thu, 18 Jan 2024 18:22:05 GMT
Content-Type: text/html
Content-Length: 597
Connection: keep-alive

**Comment by urbanogilson** [comment]
Duplicate of #25 

O problema estava no site do sicar, mas parece já ter sido resolvido.
