### ISSUE TITLE
Invalid captcha 

### ISSUE THREAD

**Issue by salesHgabriel** [urbanogilson/SICAR#27]
Após atualização do site não está sendo possível realizar download do shapefiles

![image](https://github.com/urbanogilson/SICAR/assets/40372526/00d460b5-7290-4393-9c7b-8f52406d19cd)

**Comment by urbanogilson** [comment]
Você não está usando a versão mais recente

![image](https://github.com/urbanogilson/SICAR/assets/16805527/f1b329ef-a0fa-4f91-8d80-40f60c2aed68)

Com a versão mais recente está funcionando

![image](https://github.com/urbanogilson/SICAR/assets/16805527/44e2bd29-9aaf-4a50-a8d4-1beb035c4773)

**Comment by salesHgabriel** [comment]
Não seria essa versão ? 
![image](https://github.com/urbanogilson/SICAR/assets/40372526/4bf94443-74b5-4ee8-b2ca-cf728d58dc35)

**Comment by urbanogilson** [comment]
A última versão é a 0.7.0, mas é possível perceber que a execução do seu script utiliza uma versão antiga olhando o log.
Na versão mais recente não há nada com "shapefile" https://github.com/search?q=repo%3Aurbanogilson%2FSICAR%20city&type=shapefile

O motivo pode ser devido a instalações diferentes devido aos ambientes (pipenv, virtualenv, conda, poetry, pyenv, etc)

https://xkcd.com/1987/
